### ISSUE TITLE
HTML Test Study Code 015 - CSS를 이용한 HTML활용

### ISSUE THREAD

**Issue by GunterOdimm** [GunterOdimm/HTML-Study#24]
```html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0,
minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
  <title>CSS Example</title>
  <link rel="stylesheet" type="text/css" href="css/style.css" />
</head>

<body>
  <div id="container">
    <div id="header">
      <h1 class='title'>Hello World</h1>
      <ul>
            <li> <a href="#">메일</a> </li><!--
            --><li> <a href="#">블로그</a> </li><!--
            --><li> <a href="#">카페</a> </li><!--
            --><li> <a href="#">쇼핑</a> </li><!--
            --><li> <a href="#">지식인</a> </li>
          </ul>
    </div>
    <div id="content" class="clear">
      <div id="body">
        <ul id="gallery">
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-01.jpg" alt="이미지1" /></span>
              <span class="text">바다여행에서의 피부관리 노하우</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-02.jpg" alt="이미지2" /></span>
              <span class="text">서울 시내 봄철 꽃 나들이 10선</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-03.jpg" alt="이미지3" /></span>
              <span class="text">휴식을 위한 여행</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-04.jpg" alt="이미지4" /></span>
              <span class="text">여행을 떠나기 전 체크사항</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-05.jpg" alt="이미지5" /></span>
              <span class="text">친환경이 대세다! 자전거로 떠나는 여행</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-06.jpg" alt="이미지6" /></span>
              <span class="text">야경이 아름다운 곳에서</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-07.jpg" alt="이미지7" /></span>
              <span class="text">스마트한 결혼준비 2탄</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-08.jpg" alt="이미지8" /></span>
              <span class="text">권태기가 올 줄은...</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-09.jpg" alt="이미지9" /></span>
              <span class="text">특별한 날, 완벽준비 가이드</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-10.jpg" alt="이미지10" /></span>
              <span class="text">추억의 사진 복원</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-11.jpg" alt="이미지11" /></span>
              <span class="text">일이냐, 사랑이냐. 그것이 문제로다.</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="thumb"><img src="img/thumb-12.jpg" alt="이미지12" /></span>
              <span class="text">흡연에 관한 서로의 진실</span>
            </a>
          </li>
        </ul>
      </div>
      <div id="sidebar">
        <form class='frm-login'>
            <fieldset>
                <legend>로그인</legend>
                <div>
                    <label>아이디</label>
                    <input type='text' name='user_id'
placeholder='아이디를 입력하세요'/>
                </div>
                <div>
                    <label>비밀번호</label>
                    <input type='password' name='user_id'
placeholder='비밀번호를 입력하세요'/>
                </div>
                <div>
                    <button type="button">로그인</button>
                    <button type="button">회원가입</button>
                </div>
            </fieldset>
        </form>
      </div>
    </div>
    <div id="footer">
      <address>copyright&copy;2017. itpaper.co.kr</address>
    </div>
</div>
</body>

</html>
```

**Comment by GunterOdimm** [comment]
css파일입니다
```css
@charset "utf-8";
*{
    margin: 0;
    padding: 0;
    color: #222;
    font-size: 12px;
}

a{
    text-decoration: none;
}
ul,ol{
    list-style: none;
}
#header {
    width: auto;
    background-color: #009999;
}
#header h1{
    height: 100px;
    font-size: 40px;
    text-align: center;

}
#header li{
    height: 40px;
    float: left;
    text-align: center;
    background-color: #ffffff;
    width: 20%;
    border-right: 1px dotted #cccccc;

}
#header li a{
    font-size: 20px;


}
#container{
    width: 800px;
    height: 1000px;
}

#body{
    width: 640px;
    height: ;
    float: left;
}

#sidebar {
    width: 160px;
    float: left;
}

#content{
    margin: auto;
    background-color: #FFFF00;
    height: 800px;
}
#gallery{
    height: 600px;
}
#gallery li{
    width:25%;
    float: left;
}
#gallery li a{
    display: block;
    width: auto;
    padding: 10px;
}
#gallery li a span{
    display: block;
    width: auto;
}
#gallery .thumb img{
    width: 100%;
}
#gallery .text{
    width: 95%;
    height: 30px;
    margin: auto;
    text-align: center;
    padding-top: 5px;
    padding-bottom: 10px;
}
#gallery li a:hover{
    background-color: #000066;
}
fieldset{
    height: auto;
    background-color: #ffffff;

}

address{
    font-size: 15px;
    text-align: center;
    background-color: #FF0130;
}
.clear:atfer{
    content:'';
    display: block;
    clear: both;
    float: none;
}
```
